image: maven:3-openjdk-17

stages:
  - build
  - test

cache:
  paths:
    - target/
build:
  stage: build
  script:
    - echo "Building project..."
    - mvn clean install
test:
  stage: test
  script:
    - echo "Testing project..."
    - mvn test

